from dataclasses import dataclass

@dataclass
class EarlyWarning:
    """
    Schema representing proactive warning alerts generated by scanning financial metrics.
    """
    warning_id: str
    severity: str  # Critical, Warning, Info
    category: str  # e.g., Balance, Concentration, Runway, GST, Payroll
    trigger_reason: str
    recommended_deadline: str
    affected_metric: str
    status: str  # Active, Resolved, Ignored
