from dataclasses import dataclass

@dataclass
class EmailCommunication:
    """
    Schema for email communication content generated by Gemma.
    """
    email_subject: str
    email_body: str
    tone: str
    communication_goal: str
